//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace WarehouseApplication.ECXCD {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WRSoap", Namespace="http://tempuri.org/")]
    public partial class WR : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaveWareHouseRecieptOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequestWHRCancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequestWHREditOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateWHREditDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPunOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcknowledgePunsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePUNStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveGINOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WR() {
            this.Url = global::WarehouseApplication.Properties.Settings.Default.WarehouseApplication_ECXCD_WR;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveWareHouseRecieptCompletedEventHandler SaveWareHouseRecieptCompleted;
        
        /// <remarks/>
        public event RequestWHRCancelCompletedEventHandler RequestWHRCancelCompleted;
        
        /// <remarks/>
        public event RequestWHREditCompletedEventHandler RequestWHREditCompleted;
        
        /// <remarks/>
        public event UpdateWHREditDetailsCompletedEventHandler UpdateWHREditDetailsCompleted;
        
        /// <remarks/>
        public event GetPunCompletedEventHandler GetPunCompleted;
        
        /// <remarks/>
        public event AcknowledgePunsCompletedEventHandler AcknowledgePunsCompleted;
        
        /// <remarks/>
        public event UpdatePUNStatusCompletedEventHandler UpdatePUNStatusCompleted;
        
        /// <remarks/>
        public event SaveGINCompletedEventHandler SaveGINCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveWareHouseReciept", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SaveWareHouseReciept(
                    System.Guid GRNID, 
                    string GRNNumber, 
                    System.Guid CommodityGradeId, 
                    System.Guid WarehouseId, 
                    System.Guid BagTypeId, 
                    System.Guid VoucherId, 
                    System.Guid UnLoadingId, 
                    System.Guid ScalingId, 
                    System.Guid GradingId, 
                    System.Guid SamplingTicketId, 
                    System.DateTime DateDeposited, 
                    System.DateTime DateApproved, 
                    int GRNStatusId, 
                    double GrossWeight, 
                    double NetWeight, 
                    double OriginalQuantity, 
                    double CurrentQuantity, 
                    System.Guid DepositeTypeId, 
                    int Source, 
                    double NetWeightAdjusted, 
                    System.Guid UserId, 
                    System.DateTime CreatedTimeStamp, 
                    System.Guid ClientId, 
                    int NumberOfBags, 
                    int ProductionYear, 
                    System.Guid GRNTypeId) {
            object[] results = this.Invoke("SaveWareHouseReciept", new object[] {
                        GRNID,
                        GRNNumber,
                        CommodityGradeId,
                        WarehouseId,
                        BagTypeId,
                        VoucherId,
                        UnLoadingId,
                        ScalingId,
                        GradingId,
                        SamplingTicketId,
                        DateDeposited,
                        DateApproved,
                        GRNStatusId,
                        GrossWeight,
                        NetWeight,
                        OriginalQuantity,
                        CurrentQuantity,
                        DepositeTypeId,
                        Source,
                        NetWeightAdjusted,
                        UserId,
                        CreatedTimeStamp,
                        ClientId,
                        NumberOfBags,
                        ProductionYear,
                        GRNTypeId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SaveWareHouseRecieptAsync(
                    System.Guid GRNID, 
                    string GRNNumber, 
                    System.Guid CommodityGradeId, 
                    System.Guid WarehouseId, 
                    System.Guid BagTypeId, 
                    System.Guid VoucherId, 
                    System.Guid UnLoadingId, 
                    System.Guid ScalingId, 
                    System.Guid GradingId, 
                    System.Guid SamplingTicketId, 
                    System.DateTime DateDeposited, 
                    System.DateTime DateApproved, 
                    int GRNStatusId, 
                    double GrossWeight, 
                    double NetWeight, 
                    double OriginalQuantity, 
                    double CurrentQuantity, 
                    System.Guid DepositeTypeId, 
                    int Source, 
                    double NetWeightAdjusted, 
                    System.Guid UserId, 
                    System.DateTime CreatedTimeStamp, 
                    System.Guid ClientId, 
                    int NumberOfBags, 
                    int ProductionYear, 
                    System.Guid GRNTypeId) {
            this.SaveWareHouseRecieptAsync(GRNID, GRNNumber, CommodityGradeId, WarehouseId, BagTypeId, VoucherId, UnLoadingId, ScalingId, GradingId, SamplingTicketId, DateDeposited, DateApproved, GRNStatusId, GrossWeight, NetWeight, OriginalQuantity, CurrentQuantity, DepositeTypeId, Source, NetWeightAdjusted, UserId, CreatedTimeStamp, ClientId, NumberOfBags, ProductionYear, GRNTypeId, null);
        }
        
        /// <remarks/>
        public void SaveWareHouseRecieptAsync(
                    System.Guid GRNID, 
                    string GRNNumber, 
                    System.Guid CommodityGradeId, 
                    System.Guid WarehouseId, 
                    System.Guid BagTypeId, 
                    System.Guid VoucherId, 
                    System.Guid UnLoadingId, 
                    System.Guid ScalingId, 
                    System.Guid GradingId, 
                    System.Guid SamplingTicketId, 
                    System.DateTime DateDeposited, 
                    System.DateTime DateApproved, 
                    int GRNStatusId, 
                    double GrossWeight, 
                    double NetWeight, 
                    double OriginalQuantity, 
                    double CurrentQuantity, 
                    System.Guid DepositeTypeId, 
                    int Source, 
                    double NetWeightAdjusted, 
                    System.Guid UserId, 
                    System.DateTime CreatedTimeStamp, 
                    System.Guid ClientId, 
                    int NumberOfBags, 
                    int ProductionYear, 
                    System.Guid GRNTypeId, 
                    object userState) {
            if ((this.SaveWareHouseRecieptOperationCompleted == null)) {
                this.SaveWareHouseRecieptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveWareHouseRecieptOperationCompleted);
            }
            this.InvokeAsync("SaveWareHouseReciept", new object[] {
                        GRNID,
                        GRNNumber,
                        CommodityGradeId,
                        WarehouseId,
                        BagTypeId,
                        VoucherId,
                        UnLoadingId,
                        ScalingId,
                        GradingId,
                        SamplingTicketId,
                        DateDeposited,
                        DateApproved,
                        GRNStatusId,
                        GrossWeight,
                        NetWeight,
                        OriginalQuantity,
                        CurrentQuantity,
                        DepositeTypeId,
                        Source,
                        NetWeightAdjusted,
                        UserId,
                        CreatedTimeStamp,
                        ClientId,
                        NumberOfBags,
                        ProductionYear,
                        GRNTypeId}, this.SaveWareHouseRecieptOperationCompleted, userState);
        }
        
        private void OnSaveWareHouseRecieptOperationCompleted(object arg) {
            if ((this.SaveWareHouseRecieptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveWareHouseRecieptCompleted(this, new SaveWareHouseRecieptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestWHRCancel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RequestWHRCancel(System.Guid gRNId, System.Guid userId, string remark, string trackingNumber) {
            object[] results = this.Invoke("RequestWHRCancel", new object[] {
                        gRNId,
                        userId,
                        remark,
                        trackingNumber});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RequestWHRCancelAsync(System.Guid gRNId, System.Guid userId, string remark, string trackingNumber) {
            this.RequestWHRCancelAsync(gRNId, userId, remark, trackingNumber, null);
        }
        
        /// <remarks/>
        public void RequestWHRCancelAsync(System.Guid gRNId, System.Guid userId, string remark, string trackingNumber, object userState) {
            if ((this.RequestWHRCancelOperationCompleted == null)) {
                this.RequestWHRCancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestWHRCancelOperationCompleted);
            }
            this.InvokeAsync("RequestWHRCancel", new object[] {
                        gRNId,
                        userId,
                        remark,
                        trackingNumber}, this.RequestWHRCancelOperationCompleted, userState);
        }
        
        private void OnRequestWHRCancelOperationCompleted(object arg) {
            if ((this.RequestWHRCancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestWHRCancelCompleted(this, new RequestWHRCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestWHREdit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RequestWHREdit(System.Guid gRNId, System.Guid requestedBy, string remark, string trackingNumber) {
            this.Invoke("RequestWHREdit", new object[] {
                        gRNId,
                        requestedBy,
                        remark,
                        trackingNumber});
        }
        
        /// <remarks/>
        public void RequestWHREditAsync(System.Guid gRNId, System.Guid requestedBy, string remark, string trackingNumber) {
            this.RequestWHREditAsync(gRNId, requestedBy, remark, trackingNumber, null);
        }
        
        /// <remarks/>
        public void RequestWHREditAsync(System.Guid gRNId, System.Guid requestedBy, string remark, string trackingNumber, object userState) {
            if ((this.RequestWHREditOperationCompleted == null)) {
                this.RequestWHREditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestWHREditOperationCompleted);
            }
            this.InvokeAsync("RequestWHREdit", new object[] {
                        gRNId,
                        requestedBy,
                        remark,
                        trackingNumber}, this.RequestWHREditOperationCompleted, userState);
        }
        
        private void OnRequestWHREditOperationCompleted(object arg) {
            if ((this.RequestWHREditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestWHREditCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateWHREditDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateWHREditDetails(System.Guid Id, System.Guid EditedBy, System.DateTime DateEdited, string EditDetail) {
            object[] results = this.Invoke("UpdateWHREditDetails", new object[] {
                        Id,
                        EditedBy,
                        DateEdited,
                        EditDetail});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateWHREditDetailsAsync(System.Guid Id, System.Guid EditedBy, System.DateTime DateEdited, string EditDetail) {
            this.UpdateWHREditDetailsAsync(Id, EditedBy, DateEdited, EditDetail, null);
        }
        
        /// <remarks/>
        public void UpdateWHREditDetailsAsync(System.Guid Id, System.Guid EditedBy, System.DateTime DateEdited, string EditDetail, object userState) {
            if ((this.UpdateWHREditDetailsOperationCompleted == null)) {
                this.UpdateWHREditDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateWHREditDetailsOperationCompleted);
            }
            this.InvokeAsync("UpdateWHREditDetails", new object[] {
                        Id,
                        EditedBy,
                        DateEdited,
                        EditDetail}, this.UpdateWHREditDetailsOperationCompleted, userState);
        }
        
        private void OnUpdateWHREditDetailsOperationCompleted(object arg) {
            if ((this.UpdateWHREditDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateWHREditDetailsCompleted(this, new UpdateWHREditDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPun", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CPickUpNotice[] GetPun() {
            object[] results = this.Invoke("GetPun", new object[0]);
            return ((CPickUpNotice[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPunAsync() {
            this.GetPunAsync(null);
        }
        
        /// <remarks/>
        public void GetPunAsync(object userState) {
            if ((this.GetPunOperationCompleted == null)) {
                this.GetPunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPunOperationCompleted);
            }
            this.InvokeAsync("GetPun", new object[0], this.GetPunOperationCompleted, userState);
        }
        
        private void OnGetPunOperationCompleted(object arg) {
            if ((this.GetPunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPunCompleted(this, new GetPunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AcknowledgePuns", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AcknowledgePuns(System.Guid[] punIds) {
            object[] results = this.Invoke("AcknowledgePuns", new object[] {
                        punIds});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AcknowledgePunsAsync(System.Guid[] punIds) {
            this.AcknowledgePunsAsync(punIds, null);
        }
        
        /// <remarks/>
        public void AcknowledgePunsAsync(System.Guid[] punIds, object userState) {
            if ((this.AcknowledgePunsOperationCompleted == null)) {
                this.AcknowledgePunsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcknowledgePunsOperationCompleted);
            }
            this.InvokeAsync("AcknowledgePuns", new object[] {
                        punIds}, this.AcknowledgePunsOperationCompleted, userState);
        }
        
        private void OnAcknowledgePunsOperationCompleted(object arg) {
            if ((this.AcknowledgePunsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcknowledgePunsCompleted(this, new AcknowledgePunsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdatePUNStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdatePUNStatus(System.Guid PUNId, string pUNStatusName) {
            object[] results = this.Invoke("UpdatePUNStatus", new object[] {
                        PUNId,
                        pUNStatusName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePUNStatusAsync(System.Guid PUNId, string pUNStatusName) {
            this.UpdatePUNStatusAsync(PUNId, pUNStatusName, null);
        }
        
        /// <remarks/>
        public void UpdatePUNStatusAsync(System.Guid PUNId, string pUNStatusName, object userState) {
            if ((this.UpdatePUNStatusOperationCompleted == null)) {
                this.UpdatePUNStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePUNStatusOperationCompleted);
            }
            this.InvokeAsync("UpdatePUNStatus", new object[] {
                        PUNId,
                        pUNStatusName}, this.UpdatePUNStatusOperationCompleted, userState);
        }
        
        private void OnUpdatePUNStatusOperationCompleted(object arg) {
            if ((this.UpdatePUNStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePUNStatusCompleted(this, new UpdatePUNStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveGIN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SaveGIN(System.Guid Id, string GINNumber, System.Guid PickupNoticeId, double GrossWeight, double NetWeight, double Quantity, System.DateTime DateIssued, bool SignedByClient, System.DateTime DateApproved, System.Guid ApprovedBy, string Remark, string Status) {
            object[] results = this.Invoke("SaveGIN", new object[] {
                        Id,
                        GINNumber,
                        PickupNoticeId,
                        GrossWeight,
                        NetWeight,
                        Quantity,
                        DateIssued,
                        SignedByClient,
                        DateApproved,
                        ApprovedBy,
                        Remark,
                        Status});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SaveGINAsync(System.Guid Id, string GINNumber, System.Guid PickupNoticeId, double GrossWeight, double NetWeight, double Quantity, System.DateTime DateIssued, bool SignedByClient, System.DateTime DateApproved, System.Guid ApprovedBy, string Remark, string Status) {
            this.SaveGINAsync(Id, GINNumber, PickupNoticeId, GrossWeight, NetWeight, Quantity, DateIssued, SignedByClient, DateApproved, ApprovedBy, Remark, Status, null);
        }
        
        /// <remarks/>
        public void SaveGINAsync(System.Guid Id, string GINNumber, System.Guid PickupNoticeId, double GrossWeight, double NetWeight, double Quantity, System.DateTime DateIssued, bool SignedByClient, System.DateTime DateApproved, System.Guid ApprovedBy, string Remark, string Status, object userState) {
            if ((this.SaveGINOperationCompleted == null)) {
                this.SaveGINOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveGINOperationCompleted);
            }
            this.InvokeAsync("SaveGIN", new object[] {
                        Id,
                        GINNumber,
                        PickupNoticeId,
                        GrossWeight,
                        NetWeight,
                        Quantity,
                        DateIssued,
                        SignedByClient,
                        DateApproved,
                        ApprovedBy,
                        Remark,
                        Status}, this.SaveGINOperationCompleted, userState);
        }
        
        private void OnSaveGINOperationCompleted(object arg) {
            if ((this.SaveGINCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveGINCompleted(this, new SaveGINCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CPickUpNotice {
        
        private CWarehouseReciept[] warehouseRecieptsField;
        
        private CPickupNoticeAgent[] pickupNoticeAgentsField;
        
        private System.Guid pickupNoticeIdField;
        
        private System.Guid clientIdField;
        
        private System.Guid warehouseIdField;
        
        private System.DateTime expirationDateField;
        
        private System.DateTime expectedPickupDateField;
        
        private System.Guid commodityGradeIdField;
        
        private int productionYearField;
        
        private decimal quantityField;
        
        private decimal weightField;
        
        private int statusField;
        
        private string repIdField;
        
        private System.Guid memberIdField;
        
        /// <remarks/>
        public CWarehouseReciept[] WarehouseReciepts {
            get {
                return this.warehouseRecieptsField;
            }
            set {
                this.warehouseRecieptsField = value;
            }
        }
        
        /// <remarks/>
        public CPickupNoticeAgent[] PickupNoticeAgents {
            get {
                return this.pickupNoticeAgentsField;
            }
            set {
                this.pickupNoticeAgentsField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid PickupNoticeId {
            get {
                return this.pickupNoticeIdField;
            }
            set {
                this.pickupNoticeIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid WarehouseId {
            get {
                return this.warehouseIdField;
            }
            set {
                this.warehouseIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpectedPickupDate {
            get {
                return this.expectedPickupDateField;
            }
            set {
                this.expectedPickupDateField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid CommodityGradeId {
            get {
                return this.commodityGradeIdField;
            }
            set {
                this.commodityGradeIdField = value;
            }
        }
        
        /// <remarks/>
        public int ProductionYear {
            get {
                return this.productionYearField;
            }
            set {
                this.productionYearField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string RepId {
            get {
                return this.repIdField;
            }
            set {
                this.repIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid MemberId {
            get {
                return this.memberIdField;
            }
            set {
                this.memberIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWarehouseReciept {
        
        private System.Guid idField;
        
        private System.Guid pickupNoticeIdField;
        
        private int warehouseRecieptIdField;
        
        private System.Guid gRNIDField;
        
        private string gRNNoField;
        
        private System.Guid shedIdField;
        
        private System.Guid bagTypeField;
        
        private decimal quantityField;
        
        private decimal weightField;
        
        private int bagsField;
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid PickupNoticeId {
            get {
                return this.pickupNoticeIdField;
            }
            set {
                this.pickupNoticeIdField = value;
            }
        }
        
        /// <remarks/>
        public int WarehouseRecieptId {
            get {
                return this.warehouseRecieptIdField;
            }
            set {
                this.warehouseRecieptIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid GRNID {
            get {
                return this.gRNIDField;
            }
            set {
                this.gRNIDField = value;
            }
        }
        
        /// <remarks/>
        public string GRNNo {
            get {
                return this.gRNNoField;
            }
            set {
                this.gRNNoField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ShedId {
            get {
                return this.shedIdField;
            }
            set {
                this.shedIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid BagType {
            get {
                return this.bagTypeField;
            }
            set {
                this.bagTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public int Bags {
            get {
                return this.bagsField;
            }
            set {
                this.bagsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CPickupNoticeAgent {
        
        private System.Guid idField;
        
        private System.Guid pickupNoticeIdField;
        
        private string agentNameField;
        
        private int nIDTypeField;
        
        private string nIDNumberField;
        
        private int statusField;
        
        private string agentTelField;
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid PickupNoticeId {
            get {
                return this.pickupNoticeIdField;
            }
            set {
                this.pickupNoticeIdField = value;
            }
        }
        
        /// <remarks/>
        public string AgentName {
            get {
                return this.agentNameField;
            }
            set {
                this.agentNameField = value;
            }
        }
        
        /// <remarks/>
        public int NIDType {
            get {
                return this.nIDTypeField;
            }
            set {
                this.nIDTypeField = value;
            }
        }
        
        /// <remarks/>
        public string NIDNumber {
            get {
                return this.nIDNumberField;
            }
            set {
                this.nIDNumberField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string AgentTel {
            get {
                return this.agentTelField;
            }
            set {
                this.agentTelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SaveWareHouseRecieptCompletedEventHandler(object sender, SaveWareHouseRecieptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveWareHouseRecieptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveWareHouseRecieptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RequestWHRCancelCompletedEventHandler(object sender, RequestWHRCancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestWHRCancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestWHRCancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RequestWHREditCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateWHREditDetailsCompletedEventHandler(object sender, UpdateWHREditDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateWHREditDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateWHREditDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPunCompletedEventHandler(object sender, GetPunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CPickUpNotice[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CPickUpNotice[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AcknowledgePunsCompletedEventHandler(object sender, AcknowledgePunsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AcknowledgePunsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AcknowledgePunsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdatePUNStatusCompletedEventHandler(object sender, UpdatePUNStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePUNStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePUNStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SaveGINCompletedEventHandler(object sender, SaveGINCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveGINCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveGINCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591